### ISSUE TITLE
Failure on empty topic list for credentials

### ISSUE THREAD

**Issue by kernwig** [onicagroup/cargoplane#12]
Creating credentials with an empty list of publishable topics fails to create credentials.

Example:
```
        return new CargoplaneCloud().createCredentials({
            roleName: iamRoleName,
            pubTopics: [], // clients may not publish
            subTopics: topLevelTables
        });
```

Results in:
```
Unhandled exception: { MalformedPolicyDocument: Policy statement must contain resources.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Policy statement must contain resources.',
  code: 'MalformedPolicyDocument',
  time: 2019-12-17T01:55:55.936Z,
  requestId: '5d20fbf7-2070-11ea-abf8-45e2130f2cf9',
  statusCode: 400,
  retryable: false,
  retryDelay: 99.92510993730315 }
```

**Comment by kernwig** [comment]
Released as @sailplane/cloud@1.0.2
